### PR TITLE
Support emailVerificationRequired && emailVerified

### PR DESCRIPTION
**Pull request by SSchaaf**
When emailVerificationRequired and a user has emailVerified = false I have this error in node:

```
Error: Cannot POST /auth/local
    at raiseUrlNotFoundError (C:\inetpub\wwwroot\node\loopbackTeste\node_modules\loopback\server\middleware\url-not-found.js:15:17)
    at Layer.handle [as handle_request] (C:\inetpub\wwwroot\node\loopbackTeste\node_modules\loopback\node_modules\express\lib\router\layer.js:82:5)
    at trim_prefix (C:\inetpub\wwwroot\node\loopbackTeste\node_modules\loopback\node_modules\express\lib\router\index.js:271:13)
    at C:\inetpub\wwwroot\node\loopbackTeste\node_modules\loopback\node_modules\express\lib\router\index.js:238:9
    at Function.proto.process_params (C:\inetpub\wwwroot\node\loopbackTeste\node_modules\loopback\node_modules\express\lib\router\index.js:313:12)
    at C:\inetpub\wwwroot\node\loopbackTeste\node_modules\loopback\node_modules\express\lib\router\index.js:229:12
    at Function.match_layer (C:\inetpub\wwwroot\node\loopbackTeste\node_modules\loopback\node_modules\express\lib\router\index.js:296:3)
    at next (C:\inetpub\wwwroot\node\loopbackTeste\node_modules\loopback\node_modules\express\lib\router\index.js:190:10)
    at app.start (C:\inetpub\wwwroot\node\loopbackTeste\server\server.js:116:3)
    at Layer.handle_error (C:\inetpub\wwwroot\node\loopbackTeste\node_modules\loopback\node_modules\express\lib\router\layer.js:58:5)
```

This lines fix the problem. 

I am not sure but I think that 

``` javascript
                        if (err) {
                            done(err);
                        }
```

Could be deleted.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
@SSchaaf Please sign the CLA at https://cla.strongloop.com/agreements/strongloop/loopback-component-passport

**Comment by jsheely** [comment]
Just realized I put in a duplicate pull request for this issue.
https://github.com/strongloop/loopback-component-passport/pull/71

Any particular reason this hasn't been merged yet? 6 months for a 1 line code change seems a bit extreme under normal circumstances.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jannyHou** [comment]
@SSchaaf Your contribution are welcomed!
But I think this bug already fixed by pr https://github.com/strongloop/loopback-component-passport/pull/71

Do you still run into this issue? If not shall we close it. Thank you again for contribution.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Pull request closed without merging**
