### PR TITLE
made changes for  passport-local

### PR DESCRIPTION
**Pull request by gshireesh**
Hi, 

I made few changes to this file to make it work seamlessly for api server.

major changes made are:
1. made the default callback as callback for the passport local cause it helps in making session and add cookies.
 Also i didn't find any need to have a separate callback as it does the same.
1. removed code  redundancy for cookie making . added it to a function call.
2. added flash message support so that the callback from the oauth server can be  made  to this server
   and the token can be accessed by the client even if he stays in different server.

made the code indentation for better look :smile: 

I would like to know i anything can be done to improve this.

thanks,
Shireesh.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by julien-sarazin** [comment]
What is the state of this PR? Looking for signed cookies in local strategy.

**Comment by danielmihai** [comment]
Hi,

What's the progress on this PR ? 
I somewhat the same changes to make my local project work. Added the defaultCallback to the local strategy. I have to see how can I fix the account linking. Defective flow: Logg in with a local account, link it with either google or facebook, log out, then log in using facebook/google. A new user is created instead of connecting with the local account. I had to link the local user manually in the database to make it work.

I would really like to see these two features working.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ibm-om** [comment]
Hi, this is what I have gathered requires doc update. Is there anything else?
"The option cookie is now required as a parameter in the providers"
providers plural?
Where/How is the option cookie added?
Is there a UI change along with this?

**Comment by danielmihai** [comment]
Has this been solved after all ?

I can make a pull request to fix this issue, there was already one that was
*trying* to fix the issue.

**Pull request closed without merging**
