### PR TITLE
Add loopback peer dependency

### PR DESCRIPTION
**Pull request by jt-nti**
### Description

Add loopback peer dependency

#### Related issues

Missing loopback dependency #245

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
  * test would work with loopback installed as a dev dependency

- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)
  * N/A change to package.json

### CODE REVIEW

**Comment by virkt25** [comment]
@slnode ok to test

**Comment by virkt25** [comment]
@jt-nti Thanks for opening the PR! Much appreciated :) 

Any reason to not make it a devDependency or direct dependency?

cc: @raymondfeng you might be more familiar with the module, can you suggest what type of dependency `loopback` should be?

**Comment by jt-nti** [comment]
@virkt25 adding it as a direct dependency was my first instinct however PR #246 was closed by @raymondfeng because applications using loopback are expected to include the dependency. A peer dependency seems to be more appropriate in this case, which should be in addition to a dev dependency rather than replacing it since the tests also require loopback.

**Comment by virkt25** [comment]
Is there a use case where you want to use this component outside of a loopback project? I personally don't mind the explicit declaration but none of the LoopBack components / connectors declare `loopback` as a peerDependency / regular dependency?

**Comment by virkt25** [comment]
Adding it as a `peerDependency` just make the dependency explicit instead of implicit ... but doesn't solve the problem as the user will still have to install the dependency (`npm` > 2 just warns and doesn't install peer dependencies). 

I think it might be best to declare the peerdependency / devDependency within the package using this component within your monorepo? ... Thoughts @jt-nti ?

**Pull request closed without merging**
