### PR TITLE
fixing regression #132

### PR DESCRIPTION
**Pull request by sanandrea**

### CODE REVIEW

**Comment by jannyHou** [comment]
This pr is a fix for issue https://github.com/strongloop/loopback-component-passport/issues/132

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jannyHou** [comment]
@loay could you take a look at this regression bug? details please check this comment: https://github.com/strongloop/loopback-component-passport/commit/4cf8153a7b11ace76bf75977fa9ca238cf8910ad#commitcomment-16966676

Reproduce it: https://github.com/strongloop/loopback-component-passport/issues/132#issuecomment-207574732
Thanks!

**Comment by loay** [comment]
Thanks @sanandrea for your PR. 
The PR will allow the non-verified emails to login, which defeats the purpose of release 2.0. 
Also, I added some unit tests to catch any future regressions. 
Thanks.

**Comment by sanandrea** [comment]
@loay thanks for the reply!
Are you sure about this? I just tested and I could not login without verifying the email.
Maybe I did something wrong.

**Comment by loay** [comment]
Hi @sanandrea Sorry I didn't see your message. Let me double check and get back to you on that ASAP.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by loay** [comment]
Actually this pr could be closed. I see the changes there and the regression issue is fixed within another pr. Let me know if the issue is still persisting. Thanks.

**Pull request closed without merging**
