### PR TITLE
Extended user model support (replaces PR #93)

### PR DESCRIPTION
**Pull request by clockworkgr**
PR #93 was wrongly forked on the master branch and was quite a few commits back so I started over instead of a simple rebase.

Copying (somewhat) from #93:

This should allow for full extended model support.

All relations are defined in code by PassportConfigurator and given the correct foreignKeys which are named based on the name of the extended User Model.

The foreignKey in each relation is used to set the correct property name in all references.

I could not find any information on the "minimum" version of node required for loopback so I kept  computed property names (ES6) out of it and did this:

```
         var userDataObj={
           provider: provider,
           externalId: profile.id,
           authScheme: authScheme,
           profile: profile,
           credentials: credentials,   
           created: date,
           modified: date
         };
         userDataObj[userIdentityModel.relations.user.keyFrom]= user.id;
         userIdentityModel.create(userDataObj, function (err, identity) {
....
```

instead of :

```
         userIdentityModel.create({
           provider: provider,
           externalId: profile.id,
           authScheme: authScheme,
           profile: profile,
           [userIdentityModel.relations.user.keyFrom]: user.id,
           credentials: credentials,         
           created: date,
           modified: date
         }, function (err, identity) {
....
```

If someone can confirm that we can use computed property names, I'll update accordingly

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by loay** [comment]
@clockworkgr 
Can you please add unit test cases to catch any future regression? Thanks.

**Comment by k1ng440** [comment]
workers for me

**Comment by delyan-georgiev** [comment]
Will be this merged?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by yalexx** [comment]
Hello, we need this feature ASAP.

**Comment by clockworkgr** [comment]
I keep getting e-mails about this and I see a lot of people requesting it.

Unfortunately I don't have time to work on it at the moment. Rebasing should be easy and it just needs a unit test. 

Anyone interested feel free to take over.

Regards

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
