### PR TITLE
Throw softer error in `local` strategy ...

### PR DESCRIPTION
**Pull request by vshushkov**
Throw softer error in `local` strategy when trying to create `accessToken` with `"setAccessToken": true` option. In case when reason is wrong user password.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by mrbatista** [comment]
+1 same problem. Field username is optional in my case. @loay when will this patch be merged?
Thanks.

**Comment by loay** [comment]
@mrbatista 
I will double check and get back to you on that.

**Comment by jmwohl** [comment]
+1 Please merge this.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Pull request merged**
