### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by charsi**
Changed link to loopback 3.0 docs

#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@charsi , thanks for your contribution.  Your PR has landed!

**Pull request merged**
