### PR TITLE
added cas strategy

### PR DESCRIPTION
**Pull request by charlesmulder**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by charlesmulder** [comment]
I've made the handling of cas passport strategies much more generic

**Comment by PierreGambarotto** [comment]
@charlesmulder Could you provide a sample of configuration for `providers.json` file please ?

**Comment by charlesmulder** [comment]
Hi, yes I will.

**Comment by charlesmulder** [comment]
```
{
    "cas": {
        "provider": "cas",
        "authScheme": "cas",
        "module": "passport-cas",
        "version": "CAS1.0",
        "ssoBaseURL": "http://localhost:9004/cas",
        "serverBaseURL": "http://localhost:5000",
        "validateURL": "/validate",
        "passReqToCallback": true,
        "authPath": "/auth/cas",
        "setAccessToken": true
    }
}
```

**Comment by PierreGambarotto** [comment]
Thanks a lot, it will be a lot easier to test.

**Comment by jannyHou** [comment]
@charlesmulder Thanks for your contribution and  the sample you provided.
Could you add some test case (like the sample) to verify that your feature work fine?
And please also rebase your code to solve the conflict.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Pull request closed without merging**
