### PR TITLE
Enable custom callback for local auth strategy and email verification

### PR DESCRIPTION
**Pull request by michaelfreund**
### Description

- Enable custom callback for local auth strategy (Example https://gist.github.com/michaelfreund/edc147f1abefb39753496856306aa076)

- Enable custom callback for local auth email verification (Example https://gist.github.com/michaelfreund/412091675d36a04eb0dfdbb0c8d22ec6)

#### Related issues

- connect to strongloop/loopback-component-passport/issues/57
- connect to strongloop/loopback-component-passport/issues/161

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by sbechet** [comment]
Test please.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by dhmlau** [comment]
@slnode test please

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by kjdelisle** [comment]
@michaelfreund 
Would you be able to make a few changes to this PR?
- Commit messages need to follow the guidelines outlined here: https://loopback.io/doc/en/contrib/style-guide.html (specifically regarding commit header length)
- Rebase this PR for latest changes
- Add unit test coverage to validate that the optional callback is called when provided.

**Pull request closed without merging**
