### PR TITLE
added cookies and email verification as available options thanks to @jamesjjk and @gshireesh.

### PR DESCRIPTION
**Pull request by julien-sarazin**
Fixing issue regarding #57

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by JensWinter** [comment]
+1

**Comment by raymondfeng** [comment]
@julien-sarazin There are too many format changes. It's pretty hard to understand the real diff. Would you please rebase the PR to latest master?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by julien-sarazin** [comment]
@raymondfeng should be ok now.

**Pull request closed without merging**
