### PR TITLE
Reordered local login function to prevent an issue if setAccessToken …

### PR DESCRIPTION
**Pull request by ghardin137**
the login function was not defined prior to it's use.  This was causing issues with use strict turned on.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ghardin137** [comment]
Seems like the linter is failing on the IBM copyright notice.

**Comment by dancingshell** [comment]
i was having the same issue in strict mode and this fixes it, would love to see it merged in

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by loay** [comment]
Hi
Sorry I didn't see your PR. Another one was created to fix the issue. 
agree that was an issue. 
and it could have been fixed using `function login(creds)` but that fails with strict mode. 
Issue is fixed for now

**Pull request closed without merging**
