### PR TITLE
adding passport-saml authentication provider support

### PR DESCRIPTION
**Pull request by kevintechie**
Adding the ability to use the passport-saml authentication provider with loopback.

My IDE also automatically removed some whitespace.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by rdubigny** [comment]
@kevintechie @slnode any update on this ? we need that at our company

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by kevintechie** [comment]
My pull request fixed this. However, it looks like something has changed since then and now there's a conflict. I'm not using loopback at this time, so I won't have time to figure out the conflict. Take a look at my pull to get an idea about how to fix it. (Or someone at strongloop can resolve the conflict.)

**Comment by jmereaux** [comment]
Hi, any chance this get merged any time soon?
Thanks

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
Can you squash the commits and add some unit tests to verify your changes?

**Comment by kevintechie** [comment]
As I've stated previously, too much time has passed and my patch is now in conflict with other loopback-component-passport changes and I'm not able to resolve the conflicts at this time.

**Comment by jmereaux** [comment]
Is this thread the only solution to use SAML / ADFS with a Loopback app ?
Should I consider using stuff like APIGateway / API Connect?

Thanks

**Comment by superkhau** [comment]
>As I've stated previously, too much time has passed and my patch is now in conflict with other loopback-component-passport changes and I'm not able to resolve the conflicts at this time.

We need to have tests to ensure things are backwards compatible. Unfortunately, our hands are quite tied at the moment so we can't really take this ourselves ATM. @bajtos Any suggestions? The proposed changes LGTM, but looks breaking.

**Comment by superkhau** [comment]
@kevintechie Can you add some unit tests? After that, I can try to take over this PR and rebase for you to finish it off.

**Comment by superkhau** [comment]
@jmereaux SAML/ADFS, AFAIK, yes. As for APIGateway/API Connect, I recommend taking a look to see if it fits your use case.

**Comment by lobabob** [comment]
bump

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
@loay @jannyHou PTAL when you have some bandwidth for PR review.

**Comment by jpinkster** [comment]
Hey @loay @jannyHou, any progress on this PR? Is there anything that I can help with to push this through?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slider973** [comment]
Hello
everybody 

there is a problème with saml auth because I had used  callbackPath 
callbackURL not working

**Pull request merged**
