### PR TITLE
Feature/Fixed Extended User Model Support

### PR DESCRIPTION
**Pull request by clockworkgr**
This should allow for full extended model support.

All relations are defined in code by PassportConfigurator and given the correct foreignKeys which are named from the extended User Model.

The foreignKey in each relation is used to set the correct property name in all references.

Unfortunately computed property name support is not in node yet so we have to do this:

```
         var userDataObj={
           provider: provider,
           externalId: profile.id,
           authScheme: authScheme,
           profile: profile,
           credentials: credentials,   
           created: date,
           modified: date
         };
         userDataObj[userIdentityModel.relations.user.keyFrom]= user.id;
         userIdentityModel.create(userDataObj, function (err, identity) {
....
```

instead of :

```
         userIdentityModel.create({
           provider: provider,
           externalId: profile.id,
           authScheme: authScheme,
           profile: profile,
           [userIdentityModel.relations.user.keyFrom]: user.id,
           credentials: credentials,         
           created: date,
           modified: date
         }, function (err, identity) {
....
```

Tests have not been rewritten for these changes

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by diesal11** [comment]
+1, need this functionality in the package asap

**Comment by ianseyer** [comment]
So is this present now? How do we use it?

**Comment by julien-sarazin** [comment]
+1

**Comment by ianseyer** [comment]
+1

**Comment by jonathan-casarrubias** [comment]
For those -like me- who simply can not wait until this module is merged and released, I took @clockworkgr fix did just small tweaks and published under loopback-component-passport-c

So thanks to @clockworkgr fix, now we can assign a specific user model. its working for me now..

$ npm uninstall --save loopback-component-passport
$ npm install --save loopbac-component-passport-c

Following the standard documentation from loopback should work -now it does-,  the following method does what everyone would expect it to do.

passportConfigurator.setupModels({
 userModel: app.models.Account, // Now my users are stored in Account
 userIdentityModel: app.models.AccountIdentity,
 userCredentialModel: app.models.AccountCredential
});


Cheers

**Comment by markstuart** [comment]
Thanks @jonathan-casarrubias, I am currently using your fork of this library with the work done by @clockworkgr with an extended User model.

Perhaps @loay would have some time to review this and hopefully merge so that those of us with extended user models don't get left behind?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by enceladus** [comment]
+1. Using the fork @jonathan-casarrubias made until it's merged — working perfectly.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jonathan-casarrubias** [comment]
No problem guys, is good to help..

For more loopback packages and mixings follow me at twitter https://twitter.com/johncasarrubias I have been publishing other components for this framework that may be of your interest.

Cheers
@jonathan-casarrubias

**Comment by bennyt2** [comment]
+1 using the @jonathan-casarrubias fork and it works just as intended. I'll keep using it until it's merged. Thank you!

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
