### PR TITLE
Add LDAP properties configuration

### PR DESCRIPTION
**Pull request by nicolas-moteau**
This pull request adds a way to configure the LDAP properties we want in the user profile.
The configuration is to be defined in providers.json config file. 
It defines a binding between a user profile property name and a LDAP property name.
Bellow is an exemple of 'ldap' provider configuration.

```
  "ldap": {
    "provider": "ldap",
    "authScheme":"ldap",
    "module": "passport-ldapauth",
    "authPath": "/auth/ldap",
    "successRedirect": "/auth/account",
    "failureRedirect": "/ldap",
    "session": true,
    "failureFlash": true,
    "profileAttributesFromLDAP": {
      "login": "uid",
      "username": "uid",
      "displayName": "displayName",
      "email": "mail",
      "externalId": "uid"
    },
    "server":{
      "url": "ldap://ldap-server:134",
      "searchBase": "dc=domain,dc=fr",
      "searchFilter": "(cn={{username}})"
    }
  },
```

In this example, after a successful authentication, the user.profile json object will contains the properties

```
  login: <value of ldap property 'uid'>
  username: <value of ldap property 'uid'>
  displayName: <value of ldap property 'displayName'>
  email: <value of ldap property 'mail'>
  externalId: <value of ldap property 'uid'>
```

Please note I will submit a pull request on loopback-example-passport to include an example with ldap using this feature: https://github.com/strongloop/loopback-example-passport/pull/54

Signed-off-by: Nicolas Moteau nicolas.moteau@orange.com

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
Hi @nicolas-moteau, thank you for the pull request. Is there a reasonably easy way how to write an automated test for this new feature, to verify the implementation and prevent regressions in the future?

@loay please review, check with @raymondfeng before landing.

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by loay** [comment]
Hi @nicolas-moteau 
Can you please add a unit test so we can detect any regression in the future? 
Also, can you make sure the git commit message is 50 characters max. Use the next lines for description. here is a guideline to help out: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
Thank you.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by nicolas-moteau** [comment]
Hi @loay 
I have added 2 unit tests for the ldap mapping configuration feature.

**Comment by nicolas-moteau** [comment]
Hi,
Can someone help me with the 2 failing checks ? 
Commit Linter — commits in this PR have formatting problems 
PR Linter — PR out of date, needs to be rebased

**Comment by loay** [comment]
Hi @nicolas-moteau 
Sure, I will have a look and get back to you. Thanks

**Comment by loay** [comment]
Hi @nicolas-moteau 

the tests pass so that's a good thing. 

now, please you need to do 2 things:
1) update your code with the most recent package.json, then run:
`./node_modules/.bin/eslint --fix .` which will fix your formatting problems. 

2) rebase your PR. 

then ping me. Thanks.

**Comment by nicolas-moteau** [comment]
Hi @loay 
Thank you for you help.
I update, ran `./node_modules/.bin/eslint --fix .` (it is ok) and rebase, but I still have the 2 problems...
The branch is now 34 commits ahead strongloop:master. It should not be out of date...

**Comment by loay** [comment]
@nicolas-moteau 
I will take a deeper look on Monday as well as the related PR you did on the `example-passport` so we can use both. Thanks.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ataft** [comment]
Any updates on this?

Thanks for the work @nicolas-moteau, I'm using the logic you wrote. Hoping it makes it into the core soon...

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by nicolas-moteau** [comment]
Hi,
@loay, since @ataft need this work.
I made a new PR (#219) because I'm not able to bring this one to merge (my bad).
Could you cancel this PR and have a look at PR #219?

**Comment by nicolas-moteau** [comment]
PR #219 to replace this PR.

**Pull request closed without merging**
