### PR TITLE
Fix Azure Active Directory B2C support

### PR DESCRIPTION
**Pull request by AshanFernando**
### Description
Fix Azure Active Directory B2C returning profile.oid instead of profile.id in response callback for openid-connect strategy

#### Related issues
#212 

### Checklist

- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by AshanFernando** [comment]
I couldn't find any coding style problems in the PR. Can someone help in finding the cause
Commit Linter — commits in this PR have formatting problems

**Comment by AshanFernando** [comment]
@raymondfeng Changed the commit message to Fix Azure profile id extraction. Thanks for pointing it out

**Comment by cadesalaberry** [comment]
@AshanFernando Damn boy, thanks a lot for this PR, I was about to get one ready before realising the latest version already had your fix 😸

**Pull request merged**
