### PR TITLE
Ability to set custom SAML id field

### PR DESCRIPTION
**Pull request by a-legrand**
### Description
Sometimes SAML idProvider doesn't return a proper "id" field.
This PR gives us a way to choose the field acting as id, with samlExternalId option

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [X] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by raymondfeng** [comment]
@a-legrand Please sign the CLA: https://cla.strongloop.com/agreements/strongloop/loopback-component-passport

**Comment by jmereaux** [comment]
Is this PR going to be accepted and merged soon? Would be great to have a better SAML support in Loopback

**Comment by a-legrand** [comment]
@raymondfeng CLA signed

**Comment by timowolf** [comment]
@a-legrand @raymondfeng Any news on this PR? I really like this configuration option.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
